### ISSUE TITLE
How to provide native libary

### ISSUE THREAD

**Issue by jrodmier** [mvmn/gphoto2-jna#1]
Hey,

I tried to use this api to control a DSLR in java via a Raspberry Pi 3.
I have installed libgphoto2 and gphoto2 on my Raspberry  using the sources and compiling them.

My problem occurs when I try to use this API and a get an: `java.lang.UnsatisfiedLinkError: Unable to load library 'libgphoto2.so': Native library (linux-arm/libgphoto2.so) not found`

In the `Gphoto2Library` I see `JNA_LIBRARY_NAME = "gphoto2"`.

My question: where is coming from this libgphoto2.so?

Thanks.

**Comment by mvmn** [comment]
Maybe you should use https://github.com/mvmn/gp2srv to actually control the camera - instead of using the low level API.

Best way to install libgphoto2 on Raspberry Pi so far seems to be via https://github.com/gonzalo/gphoto2-updater
The lib gets build from sources, but the script places everything where it belongs.

The .so in the name is inferred from the platform AFAIK (for Windows it would be .dll, for OS X .dylib). Not sure how this can help you though.

**Comment by jrodmier** [comment]
Ok, via https://github.com/gonzalo/gphoto2-updater, I have no more UnsatisfiedLinkError.

Thanks

**Comment by mvmn** [comment]
np
